name: Continuous Integration
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 This job was automatically triggered by the ${{ github.event_name }} event"
      - run: echo "🐧 This job is running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The branch name is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checkout code
        uses: actions/checkout@v3

      - run: echo "💡 The ${{ github.repository }} repository has been cloned."
      - run: echo "🖥️ The workflow is ready to test the code"

      - name: Running Java tests
        run: |
          mvn clean test

      - run: echo "🍏 The job status is ${{ job.status }}."

      - name: Install Node.js packages
        run: |
          cd src/main/webapp/resources/core/js
          npm install

      - name: Execute JavaScript tests
        run: |
          cd src/main/webapp/resources/core/js
          npm run test